- name: Create new ec2 instance
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        instance_type: t2.medium
        image_id: ami-0759f51a90924c166
        region: us-east-1
        key_name: EC2_SEM_KEY
        vpc_subnet_id: subnet-02debf8c477b0df78
        network:
          assign_public_ip: yes
        wait: yes
        count: 1
        security_group: eshop
        aws_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
        aws_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
        security_token: '{{ lookup("env", "AWS_SESSION_TOKEN") }}'
      register: ec2_instance_result

    - name: Add instance host to group
      add_host:
        hostname: '{{ item.public_ip_address }}'
        group_name: launched
      loop: '{{ ec2_instance_result.instances }}'

    - name: Wait for SSH connection
      delegate_to: '{{ item.public_ip_address }}'
      wait_for_connection:
        delay: 30
        timeout: 400
      loop: '{{ ec2_instance_result.instances }}'

- name: Configure EC2
  hosts: launched
  connection: ssh
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install git and docker
      apt:
        name:
          - git
          - docker.io
        state: latest
        update_cache: yes
      become: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Set rights to docker
      command: usermod -aG docker ec2-user
      become: yes

    - name: Get eshop from GIT
      git:
        repo: 'https://github.com/kokoada21/jesa02_sem.git'
        dest: ./app

    - name: Build docker with eshop
      command: docker build -t myeshop:latest ./app
      become: yes

    - name: Run docker with eshop
      command: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: yes

    - wait_for:
        port: 80
