- name: Create new ec2 instance
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        instance_type: t2.medium
        image_id: ami-0759f51a90924c166
        region: us-east-1
        key_name: EC2_SEM_KEY
        vpc_subnet_id: subnet-02debf8c477b0df78
        network:
          assign_public_ip: yes
        wait: yes
        count: 1
        security_group: eshop
        aws_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
        aws_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
        security_token: '{{ lookup("env", "AWS_SESSION_TOKEN") }}'
      register: ec2_instance_result

    - name: Add instance host to group
      add_host:
        hostname: '{{ item.public_ip_address }}'
        group_name: launched
      loop: '{{ ec2_instance_result.instances }}'

    - name: Wait for SSH connection
      delegate_to: '{{ item.public_ip_address }}'
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: '{{ ec2_instance_result.instances }}'
